#!/bin/sh
# # x-python -- Python on x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus py, with
#   no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# WHICH x-base, and why it is not one path.  The contract says a bundle's
# harness loads boot/x-base.x -- the launcher-free AMALGAM, which carries no
# path literals and so loads from any cwd.  An install has it at share/x/boot/,
# a checkout builds it into build/boot/, and neither location exists in the
# other sense.  So: probe, install layout first.
#
# lib/x-base.x is NOT a substitute.  It is the SOURCE entry and opens with
# (include "lib/x-core.x") -- a root-relative literal that resolves only with
# the cwd at the repo root, which is exactly the addressing failure this bundle
# exists to not repeat.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-python: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# x-base.x IS THE FULL-TOWER AMALGAM, which is what lets this harness match a
# bundle declaring xenon.  It carries the same tower-compiled block xe.x and
# rn.x do -- bigint, float, rational, dict -- so `2 ** 200` and `1 / 2` mean at
# the suite what they will mean at the prompt.  (x-ash's harness loads the same
# file while declaring rn; the harness has always been >= the declared dialect,
# and for py the two finally line up.)
#
# Three things here are not obvious, and each costs an afternoon:
#
# 1. %install-root FIRST.  An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree as it boots,
#    and module.x learns where that is from %install-root.
#
# 2. boot/x-base.x, NOT a dialect entry.  he.x / xe.x / rn.x end with
#    (unless %batch? (do (%banner) (repl))) and would start a REPL underneath
#    the suite.  x-base.x is the launcher-free one.
#
# 3. NEVER re-include a platform module the tower already has.  On top of a
#    booted tower that is a SEGFAULT with no diagnostic (x-lang#515), not an
#    error.  run.x owns the boot; nothing under py/ includes anything from the
#    platform.
cat > "$OUT" <<EOX
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import python/base)
(set! %repl-print %python-repl-print)
EOX
